-- The Pig pipeline is split into query-specific scripts.
-- pig/run.sh assembles this execution order at runtime:
--
--   1. common.pig
--   2. metadata.pig
--   3. q1_daily_traffic.pig, q2_top_resources.pig, and/or q3_hourly_errors.pig
--
-- Run examples:
--   ./pig/run.sh '["access_log_Jul95"]' records 10000 pig-demo all
--   ./pig/run.sh '["access_log_Jul95"]' records 10000 pig-q1 q1
